name: BTA.QuizApp

on:
  pull_request:
    branches:
      - main

jobs:
  build_dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.x'
          include-prerelease: true

      - name: dotnet build
        run: dotnet build --configuration Release

  build_react:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install React dependencies
        run: |
          cd QuizApp.Client
          npm install

      - name: Build React app
        run: |
          cd QuizApp.Client
          npm run build
